#!/usr/bin/env sh

export MOINEAU=/yocto/moineau
export IP_BAN_LIST_COUNT=1
export IP_BAN_LIST_SECONDS=60000
export FLASK_SECRET_KEY="68c80c893465f24b2a2151cd9bf9b49c3b9889823bca1a26cabf350864705429"
cd $MOINEAU
echo initializing virtual envirenment
source venv/bin/activate
echo starting application
./cam2web
echo have a nice day

